[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "pyinput-cli"
version = "0.1.0"
description = "A package for managing user input through the cli, and consistently across projects."
readme = "README.md"
requires-python = ">=3.9"
authors = [{name = "Pedro Alberto Rosquete Ares", email = "rosquetearespedro06@gmail.com"}]
license = { file = "LICENSE" }
dependencies = []

[project.urls]
Documentation = "https://github.com/prares-dev/pyinput-cli.git"
Homepage = "https://github.com/prares-dev/pyinput-cli.git"
Repository = "https://github.com/prares-dev/pyinput-cli.git"

[project.optional-dependencies]
dev = ["pytest>=8.0",]

[tool.setuptools.packages.find]
include = ["pyinput*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ['.']
addopts = "-ra"